
export default new Map([
["src/data/blog/convolutional-neural-networks.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fconvolutional-neural-networks.mdx&astroContentModuleFlag=true")],
["src/data/blog/global-id.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fglobal-id.mdx&astroContentModuleFlag=true")],
["src/data/blog/histoire-du-design-graphique.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fhistoire-du-design-graphique.mdx&astroContentModuleFlag=true")],
["src/data/blog/i18n-(internationalisation).mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fi18n-%28internationalisation%29.mdx&astroContentModuleFlag=true")],
["src/data/blog/isolation-through-contracts-making-infrastructure-independent-of-the-business-domain.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fisolation-through-contracts-making-infrastructure-independent-of-the-business-domain.mdx&astroContentModuleFlag=true")],
["src/data/blog/lazy-loading.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Flazy-loading.mdx&astroContentModuleFlag=true")],
["src/data/blog/load-balancer.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fload-balancer.mdx&astroContentModuleFlag=true")],
["src/data/blog/qu-est-ce-que-design-pattern.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Fqu-est-ce-que-design-pattern.mdx&astroContentModuleFlag=true")],
["src/data/blog/fr/convolutional-neural-networks.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Ffr%2Fconvolutional-neural-networks.mdx&astroContentModuleFlag=true")],
["src/data/blog/fr/global-id.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Ffr%2Fglobal-id.mdx&astroContentModuleFlag=true")],
["src/data/blog/fr/histoire-du-design-graphique.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Ffr%2Fhistoire-du-design-graphique.mdx&astroContentModuleFlag=true")],
["src/data/blog/fr/i18n-(internationalisation).mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Ffr%2Fi18n-%28internationalisation%29.mdx&astroContentModuleFlag=true")],
["src/data/blog/fr/isolation-par-contrats-rendre-l-infrastructure-independante-du-metier.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Ffr%2Fisolation-par-contrats-rendre-l-infrastructure-independante-du-metier.mdx&astroContentModuleFlag=true")],
["src/data/blog/fr/lazy-loading.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Ffr%2Flazy-loading.mdx&astroContentModuleFlag=true")],
["src/data/blog/fr/load-balancer.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Ffr%2Fload-balancer.mdx&astroContentModuleFlag=true")],
["src/data/blog/fr/qu-est-ce-que-design-pattern.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fdata%2Fblog%2Ffr%2Fqu-est-ce-que-design-pattern.mdx&astroContentModuleFlag=true")]]);
		